[package]
name = "zerodns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.7.0"
slog-stdlog = "4.1.1"
slog-scope = "4.4.0"
byteorder = "1.5.0"
bytes = "1.5.0"
tokio = { version = "1.36.0", features = ["full"] }
anyhow = "1.0.75"
cfg-if = "1.0.0"
clap = { version = "4.4.4", features = ["derive"] }
once_cell = "1.18.0"
futures = "0.3.28"
parking_lot = "0.12.1"
async-trait = "0.1.77"
smallvec = { version = "1.13.1", features = ["write"] }
mlua = { version = "0.9", features = ["luajit", "vendored", "serialize", "async", "macros", "send", "parking_lot"] }
ahash = "0.8"
hashbrown = "0.14"

hex = "0.4.3"
pretty_env_logger = "0.5.0"

[dev-dependencies]
