[global]
nameservers = ["223.5.5.5", "223.6.6.6"]

[server]
listen = "0.0.0.0:5454"
cache_size = 5000

[filters.lua]
kind = "lua"
props.script = """
local seq = 0
local resolvers = {
  -- Resolver('223.5.5.5', '223.6.6.6'),
  -- Resolver("https://one.one.one.one/dns-query"),
  -- Resolver("tls://dns.google"),
  -- Resolver("insecure+https://dns.google/dns-query"),
  Resolver("insecure+https://doh.pub/dns-query"),
}

-- The filter entrance:
function handle(ctx)
  ctx:nocache()

  local i = 1 + (seq % #resolvers)
  local resolver = resolvers[i]
  logger:info("use #"..tostring(i)..' resolver => '..tostring(resolver))
  seq = seq + 1

  ctx:answer(resolver:resolve(ctx.request))
end
"""

[[rules]]
domain = "*"
filters = ["lua"]
