[server]
listen = "0.0.0.0:5454"
# cache_size = 1000

[filters.test]
kind = "proxyby"
props = { servers = ["tcp://223.5.5.5"] }

[filters.china]
kind = "proxyby"
props = { servers = ["223.5.5.5", "223.6.6.6"] }

[filters.google]
kind = "proxyby"
props = { servers = ["8.8.8.8", "8.8.4.4"] }

[filters.tcpgoogle]
kind = "proxyby"
props = { servers = ["tcp://8.8.8.8", "tcp://8.8.4.4"] }


[filters.chinadns]
kind = "chinadns"
props = { trusted = ["tcp://8.8.8.8", "tcp://8.8.4.4"], mistrusted = ["223.5.5.5", "223.6.6.6"], geoip_database = "GeoLite2-Country.mmdb" }

#[[rules]]
#domain = "*bing*"
#filter = "test"
#
#[[rules]]
#domain = "*.cn"
#filter = "china"
#
#[[rules]]
#domain = "*google.com"
#filter = "google"

[[rules]]
domain = "*"
filter = "tcpgoogle"
