services:
  server:
    build: .
    command:
      - run
      - -c
      - config.toml
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./GeoLite2-Country.mmdb:/app/GeoLite2-Country.mmdb
      - ./config.toml:/app/config.toml
    ports:
      - 15454:5454/udp
      - 15454:5454/tcp
    networks:
      - local

networks:
  local:
    external: false
